<?php

namespace oheso\theme;

class theme_loader
{
    private $template_file = 'oheso-version-report_template.php';
    private $css_file   = 'oheso-version-report.css';


    private $include_template = '';
    private $include_css = '';
    private $include_css_ver = '';
    private $include_css_handle = 'oheso-version-report';

    public function __construct()
    {
        $this->set_template();
        $this->set_css();

        $this->get_report_theme();
    }


    private function set_template()
    {
        $this->include_template = locate_template( $this->template_file );
        if ( $this->include_template === '' )
        {
            $this->include_template = $this->template_file ;
        }
    }

    private function set_css()
    {
        $theme_css = locate_template($this->css_file);
        
        if ( '' === $theme_css )
        {
            $this->include_css = plugin_dir_url(__FILE__) . $this->css_file ;
            $this->include_css_ver = md5_file(plugin_dir_path(__FILE__) . $this->css_file);
        } else {
            $this->include_css = get_theme_file_uri($this->css_file);
            $this->include_css_ver = md5_file($theme_css);
        }

        wp_register_style(
            $this->include_css_handle,
            $this->include_css,
            array(),
            $this->include_css_ver,
            'all'
        );
    }

    public function get_report_theme()
    {
        $saveddata = get_option(\oheso\OHESO_OPTION_DATA);
        $saveddate = get_option(\oheso\OHESO_OPTION_DATE);

        add_filter('admin_footer_text', function(){
            echo 'This page was generated by ' . esc_html(\oheso\OHESO_PLUGIN_NAME) . ' plugin';
        });

        wp_enqueue_style($this->include_css_handle);

        include $this->include_template;
    }

}